#python -m lingua.stool config=apps/main/configs/llama2_7B.yaml nodes=32 account=fair_amaia_cw_codegen qos=lowest
dump_dir: ${oc.env:DUMP_DIR}
name: ${oc.env:WANDB_EXP_NAME}
steps: ${oc.env:STEPS}
grad_acc_steps: ${oc.env:ACCUM}

seed: 777

########################################

distributed:
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  compile: ${oc.env:COMPILE}

  dp_replicate: ${oc.env:DP_DEGREE}
  dp_shard: ${oc.env:DP_SHARD_DEGREE}
  tp_size: ${oc.env:TP_DEGREE}
  fsdp_type: ${oc.env:FSDP_TYPE}

probe_freq: ${oc.env:PROBE_FREQ}
logging_probe_result_to_wandb: ${oc.env:PROBE_WANDB}
profiling:
  run: ${oc.env:PROFILING_RUN}
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 10000
    keep: -1
  eval:
    # every: 1000
    every: 10000000000
    keep: 3

logging:
  freq: 20
  wandb: 
    project: ${oc.env:WANDB_PROJECT_NAME}
    # name: ${oc.env:WANDB_EXP_NAME}

########################################

data:
  # root_dir: data/shuffled
  root_dir: data
  sources:
    # dclm_baseline_1.0: 1.0
    # fineweb_edu_10bt: 1.0
    fineweb_edu_10bt_shuffled: 1.0
  batch_size: ${oc.env:BSZ}
  prefetch_size: 1024
  seq_len: 4096
  n_views: 2
  load_async: true
  tokenizer:
    name: tiktoken
    # path: tokenizers/cl_toplang_128k.tiktoken
    path: exp_logs/assets/tokenizers/tokenizer.model

model:
  n_layers: 32
  # dim: 512
  head_dim: 128
  n_heads: ${oc.env:N_HEADS}
  n_kv_heads: ${oc.env:N_KV_HEADS}
  ffn_dim_multiplier: 1.3
  multiple_of: 256
  rope_theta: 100_000

  mup: true
  init_base_std: ${oc.env:INIT_BASE_STD} # 1/sqrt(512)
  init_std_factor: global_depth

  # base_dim: 512
  base_head_dim: 128
  base_n_heads: ${oc.env:BASE_N_HEADS}
  base_n_kv_heads: ${oc.env:BASE_N_KV_HEADS}
  base_ffn_dim_multiplier: 1.3
  base_multiple_of: 256
  input_mult: 10.0
  output_mult: 1.0

  query_zero_init: true
  readout_zero_init: true

  fused_rms_norm: true
  # fused_ce: true

  qk_norm: ${oc.env:QK_NORM}
  residual_post_norm: ${oc.env:RES_POST_NORM}

optim:
  lr: ${oc.env:LR}
  lr_min_ratio: 0.1
  warmup: ${oc.env:WARMUP}

  clip: 1.0
  
  weight_decay: 0.0
  # weight_decay: 0.1
  # truly_decoupled_wd: true
  